// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//               'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//               'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyCqvucFTB24mDTRuz4YEmRVUcqSnWPs7Nk',
//     appId: '1:107507219050:android:82107dc0552d4ad6afe813',
//     messagingSenderId: '107507219050',
//     projectId: 'hkn-logistic',
//     authDomain: 'hkn-logistic.firebasestorage.app',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyCqvucFTB24mDTRuz4YEmRVUcqSnWPs7Nk',
//     appId: '1:107507219050:android:82107dc0552d4ad6afe813',
//     messagingSenderId: '107507219050',
//     projectId: 'hkn-logistic',
//     storageBucket: 'hkn-logistic.firebasestorage.app',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyDS-atQLVvlx59sLEd3NrNLOReJCkMXeOw',
//     appId: '1:107507219050:ios:9332cb935072f90eafe813',
//     messagingSenderId: '107507219050',
//     projectId: 'hkn-logistic',
//     storageBucket: 'hkn-logistic.firebasestorage.app',
//     iosBundleId: 'com.hkn.logistics.manager',
//   );
//
//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyDS-atQLVvlx59sLEd3NrNLOReJCkMXeOw',
//     appId: '1:107507219050:ios:40d9ac68ad888b9cafe813',
//     messagingSenderId: '107507219050',
//     projectId: 'wedding_hkn',
//     storageBucket: 'hkn-logistic.firebasestorage.app',
//     iosBundleId: 'com.example.appMobile',
//   );
// }
